apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/projectmp.git'
    targetRevision: main
    path: 'projectmp/student-management'           # path to the Helm chart in repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

