apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-management
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vivekbagde1203/projectmp.git
    targetRevision: master
    path: student-management
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

