replicaCount: 1

image:
  repository: "projectdocker1203/student-management"  # will be overwritten by Jenkins
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: student.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

