replicaCount: 1

image:
  repository: "projectdocker1203/student-management"
  tag: "v1.0.46"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: student.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

istio:
  enabled: true
  virtualService:
    hosts:
      - "*"
    gateways:
      - argocd-gateway
    http:
      - match:
          - uri:
              prefix: "/"
        route:
          - destination:
              host: student-management
              port:
                number: 8080
  destinationRule:
    host: student-management
    trafficPolicy:
      tls:
        mode: ISTIO_MUTUAL

